Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -2,24 +2,36 @@ pipeline {
   agent any
 
   environment {
-    IMAGE_NAME = "nodeapp"
-    CONTAINER_NAME = "nodeapp"
+    IMAGE_NAME = "nodeapp1"
+    CONTAINER_NAME = "nodeapp1"
     PORT = "3000"
   }
- 
- stages {
-    stage('Clean Workspace') {
+
+   options {
+        skipDefaultCheckout() // avoids automatic SCM checkout before your clone
+    }
+
+    stages {
+        stage('Prepare Workspace') {
             steps {
-                cleanWs()
+                echo "🧹 Cleaning workspace"
+                deleteDir() // wipes workspace
             }
         }
 
- stages {
-    stage('Clone') {
-      steps {
-        git branch: 'master', url: 'https://github.com/hrithik-k0/CI-CD-Project.git'
-      }
-    }
+        stage('Clone') {
+            steps {
+                echo "📥 Cloning repository"
+                sh '''
+                    if ! command -v git &> /dev/null
+                    then
+                        echo "Git not found, installing..."
+                        apt-get update && apt-get install -y git
+                    fi
+                    git clone https://github.com/hrithik-k0/CI-CD-Project.git .
+                '''
+            }
+        }
 
     stage('Build') {
       steps {
